name: Build and Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.Access_key }}
        aws-secret-access-key: ${{ secrets.Secret_access_key }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build, tag and push
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k5u0o7b3
        docker build -t team3-namegen .
        docker tag team3-namegen:latest public.ecr.aws/k5u0o7b3/team3-namegen:latest
        docker push public.ecr.aws/k5u0o7b3/namegen-team3:latest

    - name: Deploy to EKS
      run: |
        aws eks --region us-west-2 update-kubeconfig --name team3-cluster
        #for data base
        kubectl apply -f k8s_manifests/storage_svc.yml
        kubectl apply -f k8s_manifests/db_deployment.yml
        kubectl apply -f k8s_manifests/db_srvc.yml
        kubectl rollout status statefulset/mongo
        #for app
        kubectl apply -f k8s_manifests/app_deployment.yml
        kubectl apply -f k8s_manifests/app_srvc.yml
        kubectl rollout status deployment/team3-namegen
        kubectl get svc team3-namegen -o wide
